import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#656668",
        "on-secondary": "#ffffff",
        "surface": "#f7f9fb",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#cbe9f9",
        "tertiary": "#35525f",
        "surface-dim": "#d8dadc",
        "secondary-container": "#0052fe",
        "outline-variant": "#c3c5d9",
        "on-primary-fixed": "#1a1c1e",
        "on-background": "#191c1e",
        "primary-fixed": "#e2e2e5",
        "on-secondary-fixed": "#001452",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#5d5e61",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#0038b6",
        "on-surface-variant": "#434656",
        "on-tertiary-fixed-variant": "#2e4b57",
        "on-primary-fixed-variant": "#454749",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "on-secondary-container": "#dfe3ff",
        "on-tertiary-fixed": "#001f2a",
        "on-error": "#ffffff",
        "tertiary-container": "#4d6a78",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#c9e7f7",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "secondary": "#003ec6",
        "primary": "#4c4e50",
        "secondary-fixed-dim": "#b7c4ff",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dde1ff",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#c6c6c9",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#e4e4e7",
        "inverse-primary": "#c6c6c9",
        "tertiary-fixed-dim": "#adcbda",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "outline": "#737688",
        "surface-container": "#eceef0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-inter)", "sans-serif"],
        manrope: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
